name: Publish NuGet Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versión del paquete (ej: 1.2.3)"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_NAME: CQ.AuthProvider.SDK
      PACKAGE_VERSION: ${{ github.event.inputs.version }}
      NUGET_SOURCE: ${{ github.event.inputs.nuget_source }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Calculate project path
        id: paths
        run: |
          PROJECT_PATH="src/$PROJECT_NAME/$PROJECT_NAME.csproj"
          echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV
          echo "Using project path: $PROJECT_PATH"

      - name: Restore
        run: dotnet restore "$PROJECT_PATH"

      - name: Build
        run: dotnet build "$PROJECT_PATH" -c Release --no-restore

      - name: Pack
        run: |
          dotnet pack "$PROJECT_PATH" \
            -c Release \
            --no-build \
            -p:PackageVersion="$PACKAGE_VERSION" \
            -o ./artifacts

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: CodeQuality # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address
    
      # Push the package
      - name: NuGet push
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
