name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  extract_version:
    name: Extract version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract version
      id: extract_branch
      uses: battila7/get-version-action@v2

    - name: Print version
      run: echo "${{steps.extract_version.outputs.version}} ${{steps.extract_version.outputs.version-without-v}}"

  build_pack_publish:
    name: Build, pack and publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: extract_version
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set version
      run: echo "VERSION=${{ needs.extract_version.outputs.version }}" >> $GITHUB_ENV
    
    - name: Build
      run: dotnet build --configuration Release /p:Version=$VERSION
    
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=$VERSION --no-build --output .
    
    - name: Show files
      run: ls -la
    
    - name: Publish
      run: dotnet nuget push CQ.AuthProvider.SDK.$VERSION.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
